apiVersion: v1
kind: Service
metadata:
  name: {{ include "sshd-chart.fullname" . }}
  labels:
    {{- include "sshd-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "sshd-chart.selectorLabels" . | nindent 4 }}
