apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-sshd.fullname" . }}
  labels:
    {{- include "my-sshd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: sshd
  selector:
    {{- include "my-sshd.selectorLabels" . | nindent 4 }}
